# NumPuy


In [25]:
import numpy as np

In [3]:
arr= np.array([1,2,3])
print(arr)

[1 2 3]


In [8]:
ar=np.array(([1,2,3],[4,5,6],[7,8,9]))
print(ar)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
arr=np.array([1,2,3,4,5,6],ndmin=3)
print(arr.ndim)
print(arr[0])
print(arr[0][0])
print(arr[0][0][0])

3
[[1 2 3 4 5 6]]
[1 2 3 4 5 6]
1


In [14]:
arr=np.zeros([2,2])
print(arr)

[[0. 0.]
 [0. 0.]]


In [15]:
arr=np.ones([2,2])
print(arr)

[[1. 1.]
 [1. 1.]]


In [19]:
arr=np.random.rand(3,3)
print(arr)

[[0.34773335 0.08172834 0.33171342]
 [0.61888245 0.06464745 0.66113837]
 [0.58286321 0.83162428 0.777838  ]]


## Operaciones

In [21]:
arr1=[1,2,3]
arr2=[4,5,6]
arr=np.add(arr1,arr2)
print(arr)

#add, substract, multiply, divide

[5 7 9]


## Agregación

In [24]:
arr=[1,2,3]
media=np.mean(arr)
print(media)

# (media, mean), (mediana, median), (máximo, max), (mínimo, min)

2.0


## Indexación

In [26]:
arr=np.array(([1,2,3],[4,5,6]))
print(arr[1,2])

6


## Slicing

In [27]:
arr=np.array([1,2,3,4,5,6])
print(arr[::2])

[1 3 5]


In [28]:
arr=np.array([1,2,3,4,5,6])
print(arr[1:4:2])

[2 4]


## Tipos de datos